name: 'api-extractor-remap'
description: 'Remap api-extractor markdown'
inputs:
  libName:
    required: true
    description: "The name of the library api-extractor was run against"
  indexLink:
    required: true
    description: "A new link value to use for the index"
  homeLink:
    required: true
    description: "A new link value to use for home"
  path:
    required: false
    description: "Paths to run against. Globs supported."
    default: "*.md"
runs:
  using: 'node16'
  main: 'dist/index.js'
